### ISSUE TITLE
Статус проекта dsNext

### ISSUE THREAD

**Issue by dsrev** [dsrev/dsnext#1]
По какой-то причине мне захотелось форкнуть проект OpenVK Classic, который я разрабатывал вместе с крутыми челами, но в то же время мы писали очень херово. Надеемся на лучшую версию OpenVK. Да, я про второй OVK, который сейчас разрабатывается.

Всё таки, зачем я решил форкнуть проект?
* мне скучно
* решил исправить баги и дополнить функционал
* добавить что-то своё

## TODO-лист
Список в дальнейшем будет пополняться
- [ ] Исправить риски безопасности
- [ ] Соединить все модели в единую функцию и удалить тонну php файлов с корня
- [ ] Сделать полную очистку
- [ ] Переконструировать корневую директорию
- [ ] Исправить недочёты в вёрстке всего сайта
- [ ] Добавить нормальную модерацию
- [ ] Поменять дизайн всего сайта
- [ ] Смена лицензии и избавление от спорных вещей

## Небольшое сообщения для остальных текущих разработчиков OpenVK
Данный форк является экспериментальным и это не значит, что я прекращу работу над OpenVK 2.0.

**Comment by dsrev** [comment]
Что ж, _<?_ оказывается нельзя использовать и придётся изменять на _<?php_, а так же надо бы сделать предупреждение, что модуль Apache под названием "rewrite" должен быть включённым (иначе будет ошибка 500).

**Comment by dsrev** [comment]
В связи с моим переездом с Apache на nginx, думаю стоит создать примерную конфигурацию сайта для юзеров nginx.

**Comment by dsrev** [comment]
Из-за долгого неактива мне придётся начать заново
